[package]
name = "allenap-unison-confgen"
authors = ["Gavin Panella <gavin@allenap.me>"]
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = { version = "0.9.34" }                # DEPRECATED
hostname = { version = "0.4.0", features = [] }
itertools = { version = "0.12.1" }
